### ISSUE TITLE
真寻Bot

### ISSUE THREAD

**Issue by nbchihuoguo** [KroMiose/nonebot_plugin_naturel_gpt#112]
03-31 15:00:43 [ERROR] nonebot | Failed to import "nonebot_plugin_naturel_gpt"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun\zhenxun_bot\bot.py", line 16, in <module>
    nonebot.load_plugins("my_plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Program Files\py\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\zhenxun\zhenxun_bot\my_plugins\nonebot_plugin_naturel_gpt\__init__.py", line 19, in <module>
    from .config import *
  File "C:\Users\Administrator\Desktop\zhenxun\zhenxun_bot\my_plugins\nonebot_plugin_naturel_gpt\config.py", line 129, in <module>
    config = yaml.load(f, Loader=yaml.FullLoader)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-1m6aMH_A-py3.10\lib\site-packages\yaml\parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "config/naturel_gpt_config.yml", line 1, column 1
expected <block end>, but found '-'
  in "config/naturel_gpt_config.yml", line 2, column 1

**Comment by ILYSHL** [comment]
检查config/naturel_gpt_config.yml中第一行与第二行的Yaml格式是否正确
