### ISSUE TITLE
加载插件失败No module named 'regex._regex'

### ISSUE THREAD

**Issue by KiDisplayBlueScreen** [KroMiose/nonebot_plugin_naturel_gpt#129]
python版本Python 3.9.13
04-19 09:58:28 [ERROR] nonebot | Failed to import "nonebot_plugin_naturel_gpt"
Traceback (most recent call last):
  File "F:\nonebot\QQbot\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1146, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "c:\program files (x86)\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "F:\nonebot\QQbot\.venv\lib\site-packages\transformers\models\gpt2\tokenization_gpt2_fast.py", line 26, in <module>
    from .tokenization_gpt2 import GPT2Tokenizer
  File "F:\nonebot\QQbot\.venv\lib\site-packages\transformers\models\gpt2\tokenization_gpt2.py", line 23, in <module>
    import regex as re
  File "F:\nonebot\QQbot\.venv\lib\site-packages\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "F:\nonebot\QQbot\.venv\lib\site-packages\regex\regex.py", line 421, in <module>
    import regex._regex_core as _regex_core
  File "F:\nonebot\QQbot\.venv\lib\site-packages\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "c:\program files (x86)\python38\lib\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "c:\program files (x86)\python38\lib\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "c:\program files (x86)\python38\lib\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "c:\program files (x86)\python38\lib\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "c:\program files (x86)\python38\lib\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "c:\program files (x86)\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\program files (x86)\python38\lib\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "F:\nonebot\QQbot\.venv\lib\site-packages\nonebot_plugin_naturel_gpt\__init__.py", line 13, in <module>
    from .openai_func import TextGenerator
  File "F:\nonebot\QQbot\.venv\lib\site-packages\nonebot_plugin_naturel_gpt\openai_func.py", line 9, in <module>
    from transformers import GPT2TokenizerFast
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "F:\nonebot\QQbot\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1137, in __getattr__
    value = getattr(module, name)
  File "F:\nonebot\QQbot\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1136, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "F:\nonebot\QQbot\.venv\lib\site-packages\transformers\utils\import_utils.py", line 1148, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gpt2.tokenization_gpt2_fast because of the following error (look up to see its traceback):
No module named 'regex._regex'

**Comment by KroMiose** [comment]
尝试在你的nb运行环境中执行 pip install regex 或 pip install --force-reinstall regex，若仍有问题请尝试更换python版本到3.8

**Comment by KiDisplayBlueScreen** [comment]
> 尝试在你的nb运行环境中执行 pip install regex 或 pip install --force-reinstall regex，若仍有问题请尝试更换python版本到3.8
我有其他插件要3.9怎么办

**Comment by KroMiose** [comment]
3.8只是一个推荐的版本，尚无明确证据表明3.9无法使用，该问题应该是环境缺少必要的依赖导致的，如果安装regex仍出现一样的错误，请确认：
1. 报错信息是否有变化
2. pip install 执行的环境是否是nb运行的环境（注意区分虚拟环境和全局环境）

**Comment by KiDisplayBlueScreen** [comment]
> 3.8只是一个推荐的版本，尚无明确证据表明3.9无法使用，该问题应该是环境缺少必要的依赖导致的，如果安装regex仍出现一样的错误，请确认：
> 
> 1. 报错信息是否有变化
> 2. pip install 执行的环境是否是nb运行的环境（注意区分虚拟环境和全局环境）


我nb运行环境已经确认安装了regex
![image](https://user-images.githubusercontent.com/33929772/232966943-06ad5e24-194b-44e6-8eb5-9071135c5073.png)

**Comment by KroMiose** [comment]
确实是没见过的情况，如果排除了欢迎记录一下解决方式
