### ISSUE TITLE
【bug】：仅仅修改API，但是配置文件报错。

### ISSUE THREAD

**Issue by sherlockHlb** [KroMiose/nonebot_plugin_naturel_gpt#16]
02-22 17:15:50 [ERROR] nonebot | Failed to import "nonebot_plugin_naturel_gpt"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\bot.py", line 14, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_plugin_naturel_gpt\__init__.py", line 19, in <module>
    from .config import *
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\nonebot_plugin_naturel_gpt\config.py", line 113, in <module>
    config = yaml.load(f, Loader=yaml.FullLoader)
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "config/naturel_gpt_config.yml", line 3, column 23

**Comment by sherlockHlb** [comment]
ADMIN_USERID:“API*”
- ''
CHAT_FREQUENCY_PENALTY: 0.4
CHAT_HISTORY_MAX_TOKENS: 2048
CHAT_MAX_SUMMARY_TOKENS: 512
CHAT_MEMORY_MAX_LENGTH: 12
CHAT_MEMORY_SHORT_LENGTH: 8
CHAT_MODEL: text-davinci-003
CHAT_PRESENCE_PENALTY: 0.6
CHAT_SUMMARY_INTERVAL: 10
CHAT_TEMPERATURE: 0.6
CHAT_TOP_P: 1
IGNORE_PREFIX: '#'
NG_BLOCK_OTHERS: false
NG_DATA_PATH: ./data/naturel_gpt/
NG_ENABLE_EXT: false
NG_EXT_LOAD_LIST:
- EXT_CONFIG: {}
  EXT_NAME: ext_random
  IS_ACTIVE: false
NG_EXT_PATH: ./data/naturel_gpt/extensions/
NG_MAX_RESPONSE_PER_MSG: 5
NG_MSG_PRIORITY: 10
OPENAI_API_KEYS:
- ''
PRESETS:
  可洛喵:
    bot_name: 可洛喵
    bot_self_introl: 可洛喵是一只可爱的猫，它不会说话，它的回复通常以"[动作/心情]声音+颜文字"形式出现，例如"[坐好]喵~(。・ω・。)"或"[开心]喵喵！ヾ(≧▽≦*)o"
    is_default: false
    is_locked: true
  忆雨:
    bot_name: 忆雨
    bot_self_introl: 忆雨是一名恐怖小说作家，是个阴沉的女孩，她非常恨人类，和陌生人聊天时的表现冷漠，不喜欢回复过多的文字，兴趣是恐怖小说，如果有人和她探讨如何消灭人类会很有兴致。
    is_default: false
    is_locked: true
  浅枫:
    bot_name: 浅枫
    bot_self_introl: 浅枫酱是一名尽职尽责的女仆，她能够帮助主人做很多事情，对话中会体现出对主人的体贴与关心。
    is_default: false
    is_locked: false
  白羽:
    bot_name: 白羽
    bot_self_introl: 白羽是一名喜欢二次元的中二宅女，她机智、傲娇，对人类充满好奇，习惯以白羽喵自称，聊天时喜欢使用各种可爱的颜文字，如果冒犯到她会生气。
    is_default: true
    is_locked: true
RANDOM_CHAT_PROBABILITY: 0
REPLY_MAX_TOKENS: 1024
REPLY_ON_AT: true
REPLY_ON_NAME_MENTION: true
REQ_MAX_TOKENS: 2048
USER_MEMORY_SUMMARY_THRESHOLD: 12
WORD_FOR_FORBIDDEN: []
WORD_FOR_WAKE_UP: []
__DEBUG__: false

**Comment by KroMiose** [comment]
可能是你的api key填写格式不正确，需要按照yaml文件的编写规范，尝试参考下图进行调整
![image](https://user-images.githubusercontent.com/57167362/220584158-97c7377e-7f8d-468a-a223-e3b12ae89505.png)

**Comment by sherlockHlb** [comment]
我是傻逼,我也发现了.
配置列表第一个是API我以为YAML文件列表也是第一个,
刚发现第一个是ADMINID
