### ISSUE TITLE
[ERROR] pydantic_core._pydantic_core.ValidationError: 1 validation error for GlobalConfig

### ISSUE THREAD

**Issue by skytzh** [KroMiose/nonebot_plugin_naturel_gpt#201]
【Windows 10】我反复的使用了最新的pydantic=2.8版本，pydantic=2.6版本以及pydantic=1.10版本。始终报错，是不是配置代码出了什么问题？
报错信息如下：
```
08-09 01:39:40 [ERROR] nonebot | Failed to import "nonebot_plugin_naturel_gpt"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\XXX\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\XXX\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\XXX\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\XXX\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\XXX\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\XXX\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\XXX\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\XXX\.venv\Lib\site-packages\nonebot_plugin_naturel_gpt\__init__.py", line 7, in <module>
    from .config import *
  File "C:\XXX\.venv\Lib\site-packages\nonebot_plugin_naturel_gpt\config.py", line 297, in <module>
    global_config = GlobalConfig.parse_obj(driver.config)
  File "C:\XXX\.venv\Lib\site-packages\pydantic\main.py", line 1072, in parse_obj
    return cls.model_validate(obj)
  File "C:\XXX\.venv\Lib\site-packages\pydantic\main.py", line 509, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for GlobalConfig
  Input should be a valid dictionary or instance of GlobalConfig [type=model_type, input_value=Config(driver='~fastapi',...l', ng_dev_mode='False'), input_type=Config]
    For further information visit https://errors.pydantic.dev/2.6/v/model_type

```

**Comment by skytzh** [comment]
内置python版本修改为3.10解决

**Comment by F1Justin** [comment]
> 内置python版本修改为3.10，pydantic修改为1.10解决

想问一下具体是怎么操作的，是把nonebot的环境换成python 3.10吗

**Comment by KroMiose** [comment]
你需要使用python3.10来安装nb-cli，然后用其来创建整个bot项目，确保.venv中的python版本为3.10，另外pydantic仍然需要根据文档站qa中的命令来进行降级

**Comment by F1Justin** [comment]
> 你需要使用python3.10来安装nb-cli，然后用其来创建整个bot项目，确保.venv中的python版本为3.10，另外pydantic仍然需要根据文档站qa中的命令来进行降级

感谢，我来试试
