### ISSUE TITLE
[ERROR] pydantic_core._pydantic_core.ValidationError: 1 validation error for GlobalConfig

### ISSUE THREAD

**Issue by Qyyxzz** [KroMiose/nonebot_plugin_naturel_gpt#203]
也出现了与解决了一样的问题 根据大佬所说的设置 版本应该是没问题 但是就是一直出错 大佬帮看看
![85f007ebd006388c5a3ccec2561bb2e4](https://github.com/user-attachments/assets/cce5657a-f25b-42ea-8986-40a0df58632e)
![a4375ac0d84ef2412605d958219da8ff](https://github.com/user-attachments/assets/52f6a041-3d12-49ff-b246-d28174f93d9e)

**Comment by Sunderarmor** [comment]
[ERROR] nonebot | Failed to import "nonebot_plugin_naturel_gpt"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\nonebot_plugin_naturel_gpt\__init__.py", line 7, in <module>
    from .config import *
  File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\nonebot_plugin_naturel_gpt\config.py", line 297, in <module>
    global_config = GlobalConfig.parse_obj(driver.config)
  File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\pydantic\main.py", line 1162, in parse_obj
    return cls.model_validate(obj)
  File "C:\Users\zh_ha\test-qq1\.venv\Lib\site-packages\pydantic\main.py", line 596, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 1 validation error for GlobalConfig
  Input should be a valid dictionary or instance of GlobalConfig [type=model_type, input_value=Config(driver='~fastapi',....timedelta(seconds=120)), input_type=Config]
    For further information visit https://errors.pydantic.dev/2.9/v/model_type

**Comment by Sunderarmor** [comment]
我也是同样的问题，好像跟GlobalConfig相关

**Comment by KroMiose** [comment]
请查看 [文档站QA](https://ng.kro.zone/#/q_and_a?id=%e4%b8%ba%e4%bb%80%e4%b9%88%e5%87%ba%e7%8e%b0%e5%87%ba%e7%8e%b0%e9%aa%8c%e8%af%81%e9%94%99%e8%af%af%ef%bc%8c%e6%97%a0%e6%b3%95%e8%87%aa%e5%8a%a8%e7%94%9f%e6%88%90confignaturel_gpt_configyml%e6%96%87%e4%bb%b6%ef%bc%9f) 相关部分
