### ISSUE TITLE
安装插件后在notrbot根目录启动运行失败找不到插件

### ISSUE THREAD

**Issue by xsmxm** [KroMiose/nonebot_plugin_naturel_gpt#35]
![DK%LJTWQN}2I6LM 0MFN_7Y](https://user-images.githubusercontent.com/127283983/223633406-ed54508f-72da-4c05-bb72-d04c3b7a364f.png)
![YX`2Y_9Q@_UP2 IQOGP9I~8](https://user-images.githubusercontent.com/127283983/223633453-7fe83f3d-06a6-4dfc-a30f-43a161b98d88.png)

以下为运行日志
PS C:\Users\xsm\Desktop\test\first> nb run
03-08 13:51:22 [SUCCESS] nonebot | NoneBot is initializing...
03-08 13:51:22 [INFO] nonebot | Current Env: prod
03-08 13:51:22 [SUCCESS] nonebot | Succeeded to import "echo"
03-08 13:51:24 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_gocqhttp"
03-08 13:51:24 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
03-08 13:51:24 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_bing_chat"
03-08 13:51:24 [ERROR] nonebot | Failed to import "nonebot_plugin_naturel_gpt"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_naturel_gpt\__init__.py", line 19, in <module>
    from .config import *
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_naturel_gpt\config.py", line 129, in <module>
    config = yaml.load(f, Loader=yaml.FullLoader)
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\composer.py", line 58, in compose_document
    self.get_event()
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\parser.py", line 118, in get_event
    self.current_event = self.state()
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\xsm\AppData\Local\Programs\Python\Python310\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "config/naturel_gpt_config.yml", line 3, column 26
03-08 13:51:24 [SUCCESS] nonebot | Running NoneBot...
03-08 13:51:24 [INFO] uvicorn | Started server process [5580]
03-08 13:51:24 [INFO] uvicorn | Waiting for application startup.
03-08 13:51:25 [INFO] nonebot_plugin_gocqhttp | [2981563957] 当前版本:v1.0.0-rc4
03-08 13:51:25 [INFO] nonebot_plugin_gocqhttp | [2981563957] 将使用 device.json 内的设备信息运行Bot.
03-08 13:51:25 [INFO] nonebot_plugin_gocqhttp | [2981563957] 开始尝试登录并同步消息...
03-08 13:51:25 [INFO] nonebot_plugin_gocqhttp | [2981563957] 使用协议: Android Watch
03-08 13:51:25 [INFO] nonebot_plugin_gocqhttp | [2981563957] Protocol -> connect to server: 114.222.112.90:8080
03-08 13:51:25 [WARNING] nonebot_plugin_gocqhttp | [2981563957] Protocol -> device lock is disable. http api may fail.
03-08 13:51:27 [INFO] nonebot_plugin_gocqhttp | Startup complete, Web UI has served to http://0.0.0.0:28888/go-cqhttp/
03-08 13:51:27 [INFO] nonebot_plugin_apscheduler | Scheduler Started
03-08 13:51:27 [INFO] uvicorn | Application startup complete.
03-08 13:51:27 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:28888 (Press CTRL+C to quit)
03-08 13:51:28 [INFO] nonebot_plugin_gocqhttp | [2981563957] 收到服务器地址更新通知, 将在下一次重连时应用.
03-08 13:51:30 [INFO] nonebot_plugin_gocqhttp | [2981563957] 登录成功 欢迎使用: 小智bing机器人
03-08 13:51:30 [INFO] nonebot_plugin_gocqhttp | [2981563957] 开始加载好友列表...
03-08 13:51:30 [INFO] nonebot_plugin_gocqhttp | [2981563957] 共加载 13 个好友.
03-08 13:51:30 [INFO] nonebot_plugin_gocqhttp | [2981563957] 开始加载群列表...
03-08 13:51:33 [INFO] nonebot_plugin_gocqhttp | [2981563957] 共加载 8 个群.
03-08 13:51:33 [INFO] nonebot_plugin_gocqhttp | [2981563957] 资源初始化完成, 开始处理信息.
03-08 13:51:33 [INFO] nonebot_plugin_gocqhttp | go-cqhttp for 2981563957 has successfully started.
03-08 13:51:33 [INFO] uvicorn | ('127.0.0.1', 55864) - "WebSocket /onebot/v11/ws" [accepted]
03-08 13:51:33 [INFO] nonebot | OneBot V11 | Bot 2981563957 connected
03-08 13:51:33 [INFO] websockets | connection open
03-08 13:51:33 [INFO] nonebot_plugin_gocqhttp | [2981563957] アトリは、高性能ですから!
03-08 13:51:33 [INFO] nonebot_plugin_gocqhttp | [2981563957] 正在检查更新.
03-08 13:51:33 [INFO] nonebot_plugin_gocqhttp | [2981563957] 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:28888/onebot/v11/ws
03-08 13:51:33 [INFO] nonebot_plugin_gocqhttp | [2981563957] 已连接到反向WebSocket Universal服务器 ws://127.0.0.1:28888/onebot/v11/ws
03-08 13:51:33 [INFO] nonebot_plugin_gocqhttp | [2981563957] 检查更新完成. 当前已运行最新版本.
03-08 13:51:33 [INFO] nonebot_plugin_gocqhttp | [2981563957] 开始诊断网络情况
03-08 13:51:36 [INFO] nonebot_plugin_gocqhttp | [2981563957] 网络诊断完成. 未发现问题

**Comment by xsmxm** [comment]
求解答，。。

**Comment by KroMiose** [comment]
yml配置文件编辑出现问题导致无法解析，检查下配置文件是否满足yml格式要求或者找个支持yml语法的编辑器看看
