### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by SuperUnom** [KroMiose/nonebot_plugin_naturel_gpt#82]
```
03-18 21:00:54 [ERROR] logging | Traceback (most recent call last):
  File "C:\Users\Administrator\qqbot\.venv\Lib\site-packages\starlette\routing.py", line 686, in lifespan
    await receive()
  File "C:\Users\Administrator\qqbot\.venv\Lib\site-packages\uvicorn\lifespan\on.py", line 139, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

Restarted process [2112].
Shutting down process [2112]...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
object address  : 00000176F1B8CE20
object refcount : 2
object type     : 00007FFCE4E4EF70
object type name: KeyboardInterrupt
object repr     : KeyboardInterrupt()
lost sys.stderr
Stopped reloader.
```

**Comment by KroMiose** [comment]
是否开启了nb的自动重载？是的话尝试关掉

**Comment by SuperUnom** [comment]
是的，已经解决了，谢谢
